services:
 
  app:
    build: !reset null
    image: eclipse-temurin:25-jdk-alpine
    volumes:
      - .:/app
    command: ./mvnw test
    environment:
      - MAIL_VALIDATION_SECRET=qspdoifazoefnqsmlkjcncqsmdnfqmsl
      - FRONTEND_URL=http://localhost:3000 
      - DATABASE_CREATE=create
      - SQL_INIT_MODE=always
      - MAILSERVER_HOST=mailserver
      - MAILSERVER_PORT=1025
      - DATABASE_URL=jdbc:mariadb://database:3306/springinn?user=dev&password=1234
  